repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12
        entry: black
        require_serial: true

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        language_version: python3.12

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        language_version: python3.12

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        language_version: python3.12
        additional_dependencies: [
          'types-Flask-SQLAlchemy',
          'types-Flask-WTF',
          'types-Werkzeug',
          'sqlalchemy[mypy]'
        ]
        args: [--ignore-missing-imports]
        additional_dependencies:
          - "sqlalchemy>=2.0.0"
          - "flask"
          - "flask-sqlalchemy"
          - "flask-login"
          - "flask-wtf"
          - "python-dotenv"
          - "pytest"
          - "email_validator"
          - "pypinyin"
          - "gunicorn"
          - "wtforms"

  - repo: local
    hooks:
      - id: pytest
        name: pytest unit tests
        entry: pytest
        language: python
        types: [python]
        additional_dependencies:
          - pytest
          - flask
          - sqlalchemy
          - flask-sqlalchemy
          - flask-login
          - flask-wtf
          - python-dotenv
          - email_validator
          - pypinyin
          - gunicorn
        pass_filenames: false
