repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        language_version: python3

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        language_version: python3

  - repo: local
    hooks:
      - id: mypy
        name: mypy type checking
        entry: poetry run mypy
        language: system
        types: [python]
        require_serial: true
        additional_dependencies:
          - "sqlalchemy"
          - "types-sqlalchemy"
          - "types-flask-sqlalchemy"
          - "types-Flask"
          - "types-Werkzeug"
          - "types-click"
          - "types-setuptools"

  - repo: local
    hooks:
      - id: pytest
        name: pytest unit tests
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
