name: Python CI/CD

on:
  push:
    branches:
      - main
      - feature/flask-factory-pattern
  pull_request:
    branches:
      - main
      - feature/flask-factory-pattern
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8.2'

      - name: Configure Poetry and Verify Installation
        run: |
          poetry config virtualenvs.in-project true
          echo "--- Verifying Poetry Installation ---"
          poetry --version
          which poetry
          echo "Current PATH: $PATH"
          echo "--- End Verification ---"

      - name: 配置 PyPI 镜像为清华源
        run: poetry config repositories.pypi https://pypi.tuna.tsinghua.edu.cn/simple

      - name: Install dependencies with Poetry
        run: poetry install --no-root

      - name: Run pre-commit checks
        run: poetry run pre-commit run --all-files

      - name: Run Pytest tests
        run: poetry run pytest
